### ISSUE TITLE
我发现了几个BUG

### ISSUE THREAD

**Issue by TCBocean** [qxde01/keras-alchemy#1]
无意间看到了你的项目，挺适合入门学习的。
我的环境：
```
tensorflow-gpu 2.0
keras 2.3.1
windows 10
```
我直接运行train_cifar100_classify.py时发现了以下问题：
1.在tensorflow2.0上，运行会报错，也可能是我使用的方法有问题吧。我现在直接使用keras运行没有问题。
2.  
https://github.com/qxde01/keras-alchemy/blob/c4cca10d42ccdbdf6d1af044b48b404e851f898b/train_cifar100_classify.py#L83
这行代码中的val_acc要换成val_accuracy，否则key不对会报错。
3.saved文件夹没有默认创建，需要手动创建，若不存在此文件夹会报错。希望加个提醒。

另外radam也需要手动下载，希望加个提示。
`pip install keras-rectified-adam`

还有还有，tensorboard记录方式很诡异，居然记录的是每个周期的损失，曲线看上去就很诡异，希望改为记录整个训练过程的损失的形势。3Q

**Comment by TCBocean** [comment]
今天我又尝试在Ubuntu上运行了代码
我的环境：
tensorflow-gpu 1.12
keras 2.2.4
Ubuntu16.04
我发现：
1.val_acc要换成val_accuracy不是BUG，而是库的版本问题。
2.相同的代码，在windows上不能收敛，在Ubuntu上可以收敛，很神奇，我打算去论坛里问问。
3.mobilenetv3模型builder的输入参数有一个名称错了。

**Comment by qxde01** [comment]
这份代码都是来自keras的修改，tf2.0 需要关闭eager模式 `tf.compat.v1.disable_eager_execution()`,只测试过mixnets（win10），谢谢你的建议.
另外我自己也跑不出 pytorch-cifar100上的精度

**Comment by TCBocean** [comment]
emmmmm，精度上的确无法收敛到paper的结果。
不过这个项目挺棒的~
